FROM dunglas/frankenphp:1-php8.4-alpine

RUN install-php-extensions pdo_mysql opcache
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /app
COPY Caddyfile /etc/caddy/Caddyfile
COPY src ./src
COPY public ./public

ENV PORT=80
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
